### ISSUE TITLE
Auto-prefixer

### ISSUE THREAD

**Issue by dougse** [excubo-ag/WebCompiler#1]
Thanks for taking a shot at this - Please add support for auto-prefixer.

**Comment by stefanloerwald** [comment]
Hi @dougse,

Thanks for your request. These feature seems to be feasible by using [this library](https://github.com/Taritsyn/AutoprefixerHost). At the moment, I can't give you an estimate for when I could implement this myself, as I'm busy with some other projects. Would you be willing to contribute this as a pull request?

BR
Stefan

**Comment by elken** [comment]
I would also be interested in this so I've started implementing it. I have a simple working version that correctly prefixes.

# Before
![image](https://user-images.githubusercontent.com/2872862/93641254-e1ddcc80-f9f3-11ea-90ce-b76a4269fe97.png)

# After
![image](https://user-images.githubusercontent.com/2872862/93641307-f6ba6000-f9f3-11ea-834a-aec59aeb4389.png)

I just need to check it covers, make all the tests pass & add some more tests.

**Comment by stefanloerwald** [comment]
Thanks to @elken, this feature is available starting with version 2.5.0.
