### ISSUE TITLE
Compatibility: Package Excubo.WebCompiler 2.4.2 is not compatible with netcoreapp3.1

### ISSUE THREAD

**Issue by furcan** [excubo-ag/WebCompiler#12]
Hi,

Thanks for the extension but I could not try yet as well because of the issue as below :) 

![Capture](https://user-images.githubusercontent.com/49978011/93721173-b7784480-fb96-11ea-88a7-669db49afb86.PNG)

Thank you in advance.

**Comment by stefanloerwald** [comment]
Hi @furcan,

this is not an issue with the compatibility, but an issue of how to install webcompiler. The third error line gives you the actual error:

> Invalid project-package combination for Excubo.WebCompiler 2.4.2. **DotnetToolReference** project style can only contain references of the DotnetTool type.

This package is a dotnet tool, therefore cannot be installed as a package reference. See also #4 and the [Getting started](https://github.com/excubo-ag/WebCompiler#getting-started) section of the Readme.

**Comment by stefanloerwald** [comment]
Considered a duplicate of #13
