### ISSUE TITLE
Any chance there is a way to make it work as an ordinary nuget package

### ISSUE THREAD

**Issue by szalapski** [excubo-ag/WebCompiler#14]
If I install it as a .NET tool, that means my team has to always install it too.  This is a deal-breaker for me.  Any chance there is a way to make it work as an ordinary nuget package?  Thanks either way.

**Comment by stefanloerwald** [comment]
Hi @szalapski, this is partially answered in #13. While it's possible to create such a nuget package, I believe it would make using the tool much less convenient.

There is a way to make life easier for your team though: Use it as local tool https://github.com/excubo-ag/WebCompiler#local
and/or make the installation of the tool a build step that the actual build step depends on.

**Comment by elken** [comment]
As mentioned you can install as a local tool with dotnet tool and the tool will get pulled in as needed. Also pulls in for CI.

**Comment by stefanloerwald** [comment]
Hi @szalapski,

@elken has improved the documentation for local tools. Please have a look at this section as well: https://github.com/excubo-ag/WebCompiler#local-1

Please let us know whether this is now satisfactory to you.

BR
Stefan
