### ISSUE TITLE
Segmentation fault when running in alpine docker container using sdk:3.1-alpine MS image

### ISSUE THREAD

**Issue by James-1064** [excubo-ag/WebCompiler#18]
Using as a base build image mcr.microsoft.com/dotnet/core/sdk:3.1-alpine 

I have installed webcompiler as a global tool, but when i execute webcompiler, it returns a Segmentation fault error.

If i open an interactive shell to the container and enter: webcompiler, i get the help txt showing options.
If i enter the command: webcompiler -r Client/scss -c webcompilerconfiguration.json
I get the error.

Configuration is just the standard config with gzip set to false

Any help much appreciated.

**Comment by stefanloerwald** [comment]
Hi @James-1064,

I can in fact reproduce this issue. Not sure what's going wrong here. This is not reproducible with net5.0. I strongly suggest to update to net5.0. If this is not possible for your entire build, you can still use this as a build step and copy the result into the 3.1 build.

BR
Stefan

**Comment by James-1064** [comment]
Thanks for the quick response !

I don't think net5.0 is ready for production use, so that's going to be a non starter. 
Now looking into node and gulp with gulp-sass in a build container for creating images, this can be used in the CI/CD pipeline.

We will continue to use this package for local development.
Thanks again !

**Comment by elken** [comment]
Rc1 being released signifies it is ready for production use.

**Comment by stefanloerwald** [comment]
Hi @James-1064,

net5.0 is very much ready for production use. It has been officially supported since RC1, and today is the full release of net5.0.

Currently, there's a strong argument to use dart-sass, as libsass is officially deprecated. At the moment, there's sadly no library yet to incorporate dart-sass into a dotnet tool. As soon as that's available, excubo.webcompiler will switch over.

**Comment by elken** [comment]
@James-1064 https://devblogs.microsoft.com/dotnet/announcing-net-5-0/
