### ISSUE TITLE
Feature Request: Support for file-specific settings.

### ISSUE THREAD

**Issue by MaverickMartyn** [excubo-ag/WebCompiler#19]
Hi there!

I just started fiddling with this tool, coming from Mads Kristensens extension, and I'll say while it's not quite as plug-and-play, I do like it.
One feature I'm missing is the ability to define settigns for individual files, where needed, like Mads's version could.
Sometimes you want some files to go in some directories and others to go elsewhere.

Thank you for your hard work. :)

**Comment by elken** [comment]
You can use build tasks to move whatever files you want.

**Comment by stefanloerwald** [comment]
Hi @MaverickMartyn,

this would require quite some fundamental changes to the design of this tool, while - as @elken said - this can also be achieved with a handful of build tasks. With that, I don't see a huge benefit of adding this feature. Should you still want it, please consider sharing your idea on how to achieve that and creating a pull request, which I'd happily review.

Thanks
Stefan
