### ISSUE TITLE
Compile on file change or on save

### ISSUE THREAD

**Issue by rwasef1830** [excubo-ag/WebCompiler#2]
Hello,
Is there a way to run automatically on scss file save or have it watch file changes ?

**Comment by rwasef1830** [comment]
I was able to make it work:

Editing csproj:
```xml
<ItemGroup>
    <Watch Include="**\*.scss" />
</ItemGroup>
```

Then run from the console in the project folder:
```
dotnet watch tool run webcompiler -c webcompilerconfiguration.json -r wwwroot
```

Perhaps documentation should cite such example.

**Comment by softlion** [comment]
Is it possible to have the same behavior as in mad christensen's version ?
Ie: compiles on save without having to use a dotnet watch command line in another window.

Maybe by implementing an additional "nuget local tool" that you add to the project, like analyzers do.

Also are you on discord's dotnetevolution ?

**Comment by stefanloerwald** [comment]
Hi @softlion,

There's no plan to implement such a version, as it's significant effort for not much benefit. Have a look at https://github.com/excubo-ag/WebCompiler#msbuild. This shows you how to effectively get the same behavior. 

Hope this helps
Stefan

**Comment by KKacer** [comment]
I think I have a problem in enabling the watch or the command tool definition.

I get this error:
`Could not find a MSBuild project file in 'D:\HIH'. Specify which project to use with the --project option.`

I tried the given syntax as well as the below code: (tried both)

`dotnet watch tool run webcompiler -c webcompilerconfiguration.json -r wwwroot --project HIH\HIH.csproj`

Did I miss anything?

@stefanloerwald @rwasef1830

**Comment by rwasef1830** [comment]
I always run it from the project folder, never tried --project switch before.

**Comment by stefanloerwald** [comment]
This is an issue with how dotnet tool works and unrelated to webcompiler.

**Comment by KKacer** [comment]
@stefanloerwald fine,
I fixed that,
By the way, what about this issue:

https://postimg.cc/18CZxg4q
https://i.postimg.cc/QMsNT130/qq.png

Earlier I enabled webcompiler globally, and had no issues.
Should I create the **tool manifest** for any project, in its project directory?

**Comment by stefanloerwald** [comment]
Sorry but again, this is an issue with how dotnet tool works and I can't offer any help on that. It's not in scope for this project.
