### ISSUE TITLE
Recompile tests fail on unix

### ISSUE THREAD

**Issue by stefanloerwald** [excubo-ag/WebCompiler#22]
There are two tests in https://github.com/excubo-ag/WebCompiler/blob/main/Tests_WebCompiler/RecompileTests.cs which fail on unix. Investigation is needed here.

**Comment by mikes-gh** [comment]
When you say unix do you mean linux?
case sensitivity?

**Comment by stefanloerwald** [comment]
I do mean Linux. The issue is presumably with file timestamps, but I have yet to set up a test that shows me.
