### ISSUE TITLE
unknown command

### ISSUE THREAD

**Issue by mshakurov** [excubo-ag/WebCompiler#27]
run webcompile from console or MSBuild Task:

`dotnet tool run webcompiler -r themes -o wwwroot/css -z disable -m disable -p disable`

result: 
exit code: 1
messages: 
```
unknown command or argument "-r"
unknown command or argument "themes"
unknown command or argument "-o"
unknown command or argument "wwwroot/css"
```
... 
etc.

what I do wrong?

**Comment by stefanloerwald** [comment]
Hi @mshakurov 

I don't know what's going wrong there, because the following works perfectly fine for me:

```ps
dotnet new tool-manifest
dotnet tool install Excubo.WebCompiler
mkdir themes
dotnet tool run webcompiler -r themes -o css -z disable -m disable -p disable
```

So this isn't an issue with webcompiler, as far as I can see. Maybe you're using a shell that is misbehaving? The above I've tried with Powershell on Windows 10.

Stefan
