### ISSUE TITLE
Stop webcompiler from touching source files

### ISSUE THREAD

**Issue by aarivex** [excubo-ag/WebCompiler#28]
First of all I'd like to say that I really like this project because its simple and provides a neat alternative to Node/npm solutions, as a lot of them just add more complexity and are often painful to configure, especially for the first time.

I set up my project file so that it runs webcompiler on every build, and it works flawlessly.
Though there is something that bugs me - the source file, at least the .scss file, is getting edited.

Every time I run webcompiler, the indentation of the source file is being trimmed and a sourceMap comment appears in the last line.
Example:

```sass
body {
  background: #fafafa; }
/*# sourceMappingURL=resources\css\app.css.map */
```

Is there a way to disable this behavior?

Thanks.

**Comment by stefanloerwald** [comment]
Hi @aarivex,

normally this should be possible by adjusting the `SourceMap` feature of the sass compiler. See the [configuration section in this project's Readme](https://github.com/excubo-ag/WebCompiler#configuration). However, I just noticed that there is a bug in our code that made this setting be ignored for the sass compilation step. A new version (2.6.10) will be available in a few minutes fixing this.

BR
Stefan

**Comment by aarivex** [comment]
Hi!

Thanks for the response and update.
I initially disabled the SourceMap property in the configuration file, yet it was ignored as you stated.

**Comment by stefanloerwald** [comment]
Hi,

is it working as expected with v2.6.10 now?

Thanks for your feedback
Stefan

**Comment by aarivex** [comment]
I don't know what happened, but strangely it doesn't override my source file anymore. Its still the same version.

I'll further evaluate and get back to you soon! Thanks.

**Comment by aarivex** [comment]
I can't track why it suddenly stopped changing the source file.

I'll just update to the latest version. Really weird.

**Comment by stefanloerwald** [comment]
Hi @aarivex,

is this issue resolved or are you continuing to experience this unwanted behaviour?

Thanks for your feedback
Stefan

**Comment by aarivex** [comment]
Hey!

I gladly didn't face any issues yet. Thanks for checking!
