### ISSUE TITLE
The command "dotnet tool run webcompiler" exited with code 1 in github workflow but no usefull error

### ISSUE THREAD

**Issue by Liero** [excubo-ag/WebCompiler#29]
Hi,

I have added following target to my .csproj:

```xml
  <Target Name="CompileStaticAssets" AfterTargets="AfterBuild">
    <Exec Command="dotnet tool run webcompiler -c webcompilerconfiguration.json -f webcompilerfiles.conf" StandardOutputImportance="high" />
  </Target>
```

It works locally, but it suddenly stopped working in my github actions (it was working previously):
```
 CompileStaticAssets:
         dotnet tool run webcompiler -c webcompilerconfiguration.json -f webcompilerfiles.conf
         Expected expression, found '$'
         Expected expression, found '$'
         Expected expression, found '$'
         Expected expression, found '$'
     2>/home/runner/work/vNext.BlazorComponents/vNext.BlazorComponents/BlazorComponents/vNext.BlazorComponents.csproj(49,5): error MSB3073: The command "dotnet tool run webcompiler -c webcompilerconfiguration.json -f webcompilerfiles.conf" exited with code 1.
```

**It does not provide any useful error message, nor the source of the error.**

Entire github actions log can be found [here](https://github.com/Liero/vNext.BlazorComponents/runs/2235418630?check_suite_focus=true#step:6:370), including [souce codes](https://github.com/Liero/vNext.BlazorComponents/)

I'm using v2.6.6., see [log](https://github.com/Liero/vNext.BlazorComponents/runs/2235418630?check_suite_focus=true#step:4:6)

**Comment by stefanloerwald** [comment]
Hi @Liero,

this points towards an error within a compilation process, not in this project. Let me see whether I can provide more information about the source of the error. In any case, I'd recommend you to always upgrade to the most recent release, as it is regularly updated whenever one of the libraries receives an update.

BR
Stefan

**Comment by stefanloerwald** [comment]
Hi @Liero,

I've just pushed a new version (2.7.0) which should improve error source information. Please test your workflow with this version.

BR
Stefan

**Comment by Liero** [comment]
Thanks. Is something wrong with the release or it is just a nuget cache?

> dotnet tool install --global Excubo.WebCompiler --version 2.7.0
error NU1102: Unable to find package excubo.webcompiler with version (>= 2.7.0)
error NU1102:   - Found 48 version(s) in NuGet [ Nearest version: 2.6.10 ]
error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
error NU1102:   - Found 0 version(s) in C:\Program Files\dotnet\sdk\NuGetFallbackFolder
The tool package could not be restored.
Tool 'excubo.webcompiler' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by stefanloerwald** [comment]
This is very likely to be a nuget cache issue. `dotnet restore` knows `--no-cache`, but unfortunately `dotnet tool` doesn't yet (https://github.com/dotnet/sdk/issues/9577, just as `dotnet new` doesn't https://github.com/dotnet/templating/issues/2874). IIRC the cache lasts 30 minutes, so you should be fine within a few minutes.

**Comment by Liero** [comment]
Thanks. The error output is now crystal clear. perfect.

> dotnet tool run webcompiler -c webcompilerconfiguration.json -f webcompilerfiles.conf
Expected expression, found '$'
-- in file wwwroot\SimpleGrid.css L5:23
Expected expression, found '$'
-- in file wwwroot\SimpleGrid.css L6:26
Expected expression, found '$'
-- in file wwwroot\SimpleGrid.css L7:26
Expected expression, found '$'
-- in file wwwroot\SimpleGrid.css L8:29

I my case there was a breaking change in recent sass compiler and on my local env I've been using older version. 

Not sure why dotnet prefered global installed package over local package in dotnet-tools.json.
