### ISSUE TITLE
Is there a version of WebCompiler that can work with .NET Core 2.2?

### ISSUE THREAD

**Issue by scobie-reclip** [excubo-ag/WebCompiler#34]
I'm working on a project is stuck for now using .NET Core 2.2. I tried installing the latest NuGet, which now is 2.7.2, but it requires .NET 5 or higher.
I see earlier versions of the NuGet. Is there a point, going back, when .NET Core 2.2 was supported? I might use that for now, until we upgrade our .NET in a few weeks.
Thanks.
Scobie

**Comment by scobie-reclip** [comment]
I can add that I have tried installing the earliest version visible in the package manager in Visual Studio 2019, which is 1.0.4. But it requires .NET Core 3.1. That looks like your earliest release. So, I guess the answer is no...

**Comment by stefanloerwald** [comment]
It sounds to me like you're trying to install this tool as a package dependency, which is never going to do what you would want. Sadly nuget doesn't understand that (yet). Here are more details about it: https://github.com/excubo-ag/WebCompiler/issues/13
