### ISSUE TITLE
net6 support

### ISSUE THREAD

**Issue by mikes-gh** [excubo-ag/WebCompiler#35]
Does the library support net6
I can build and test locally with net5 sdk and net6 sdk installed but the CI build fails where only net6.0 is installed

```
  Tool 'excubo.webcompiler' (version '2.6.5') was restored. Available commands: webcompiler
  
  Restore was successful.
  It was not possible to find any compatible framework version
  The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.
    - The following frameworks were found:
        6.0.0-preview.5.21301.5 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by mikes-gh** [comment]
Probably we only need net6.0 here
https://github.com/excubo-ag/WebCompiler/blob/a577331deea5ffa4eb62e57256791847bea891b3/WebCompiler/WebCompiler.csproj#L5

**Comment by stefanloerwald** [comment]
Hi @mikes-gh,

Yes, that should work without any issue. I won't be able to do that before Monday, so if you need it urgently, please just create a PR for me to merge (update csproj also for the version number in package.csproj).

Thanks
Stefan

**Comment by stefanloerwald** [comment]
A few files needed adjustment, but trivial, as you suspected. Support added with https://github.com/excubo-ag/WebCompiler/commit/5b8ac2ba604a9bd9e81a95061cac6bd2a73e159f and https://github.com/excubo-ag/WebCompiler/commit/f6c6e9e87bcce412ce3e12ee98b46adc12651407

Please let me know whether everything works as you expect it to in v2.7.12.

Thanks
Stefan

**Comment by mikes-gh** [comment]
@stefanloerwald Thanks for the update.  I can report it all works well now with only the 6.0.x SDK in pipeline
