### ISSUE TITLE
dart-sass support

### ISSUE THREAD

**Issue by Liero** [excubo-ag/WebCompiler#37]
Hi,

just FYI, there is a preview 2 release of [DartSassHost](https://github.com/Taritsyn/DartSassHost/releases). 

It would be great, if you could  test it out. Thanks

**Comment by stefanloerwald** [comment]
Hi @Liero, 

Thanks for getting in touch. I am aware of `DartSassHost` and awaiting the first non-preview release. I've already experimented with `DartSassHost` and everything is looking good. For now, things will stay in PR stage (https://github.com/excubo-ag/WebCompiler/pull/38). I don't think the project should depend on a preview version of any package.

BR
Stefan

**Comment by Liero** [comment]
> I don't think the project should depend on a preview version of any package.

Definitely not, but you could theoretically release a preview version as well. The point is to find potential bugs in `DartSassHost` before final release and this is best IMO way

**Comment by stefanloerwald** [comment]
> > I don't think the project should depend on a preview version of any package.
> 
> Definitely not, but you could theoretically release a preview version as well. The point is to find potential bugs in `DartSassHost` before final release and this is best way, IMO

Good idea, I'll do that!

**Comment by stefanloerwald** [comment]
I'm getting build failures (https://github.com/excubo-ag/WebCompiler/runs/3192991097?check_suite_focus=true), probably more related to net6 than to dartsass. I'll have to investigate, so the release of the first preview version might be a while.

**Comment by stefanloerwald** [comment]
@Taritsyn was able to help me with the issue I was experiencing (https://github.com/Taritsyn/DartSassHost/issues/2), which means [v3.0.0-preview-1](https://www.nuget.org/packages/Excubo.WebCompiler/3.0.0-preview-1) is now available.

**Comment by Liero** [comment]
DartSassHost is stable now
