### ISSUE TITLE
.NET Standard 2.1 Support

### ISSUE THREAD

**Issue by Schuttrim** [excubo-ag/WebCompiler#4]
Would It be possible to support .NET Standard? 

It would enable the package to be viable for WASM Blazor Apps and Libraries.

**Comment by stefanloerwald** [comment]
Hi @Schuttrim 

This tool is not one that is added as a package to projects. The way to install it is via `dotnet tool install --global Excubo.WebCompiler`. So this is already compatible with Blazor.

**Comment by stefanloerwald** [comment]
Considered a duplicate of #13
