### ISSUE TITLE
dotnet watch example gives error: Cannot find a tool 'webcompiler'

### ISSUE THREAD

**Issue by mejobloggs** [excubo-ag/WebCompiler#41]
When I run `dotnet watch tool run webcompiler`

I get the error `Cannot find a tool in the manifest file that has a command named 'webcompiler'`

Scss compiles fine via project file with this:
```
<Target Name="CompileStaticAssets" AfterTargets="AfterBuild">
    <Exec Command="webcompiler -f files.conf" StandardOutputImportance="high" />
  </Target>
```
But would like to get dotnet watch working, and don't understand how

**Comment by stefanloerwald** [comment]
Hi @mejobloggs,

it sounds to me that you installed webcompiler as a global tool, not specific to this project. Try installing it as a local tool too.

Hope that helps,
Stefan

**Comment by mejobloggs** [comment]
Thanks, it seems I needed to install it both global and local
