### ISSUE TITLE
Does this work for .Net Framework?

### ISSUE THREAD

**Issue by THammond9** [excubo-ag/WebCompiler#42]
Maybe this has an obvious answer but I don't see a compatibility table in the info for this project. We are stuck on 4.6.1 but I would like to use a scss compiler that is being maintained. While I think it might work if the PC that is doing the build has .NET Core installed I am not sure if there are some assumptions about the solution or project file structures that are different and would prevent this tool from running properly.

**Comment by stefanloerwald** [comment]
Hi @THammond9. This tool does not care about any project structure and actually doesn't even need any. It therefore works if any of the dotnet core version is installed on the machine (which you need to run `dotnet install`), regardless of project TFM.
