### ISSUE TITLE
Javascript: Support class variables

### ISSUE THREAD

**Issue by NullQubit** [excubo-ag/WebCompiler#48]
Minification for classes with explicitly defined class fields fails. Example:

```
class A {
    field;

   constructor() { 
    }
}
```

The above is supported in NUglify from v1.16.0.

**Comment by stefanloerwald** [comment]
Hi @NullQubit,

Thanks for raising this! Seems like this update slipped my attention. I'm in the process of deploying an updated version, so you should be able to update within the next hour.

Best regards,
Stefan
