### ISSUE TITLE
compiled css does not include changed partials unless main scss file is changed

### ISSUE THREAD

**Issue by devjklein** [excubo-ag/WebCompiler#51]
I have a primary site.scss file and several directories such as base, layout, components, etc, containing my styles. The site.scss only includes the following content:

```
@import url("open-iconic/font/css/open-iconic-bootstrap.min.css");
@import "base/variables", // New SASS variables first
        "base/root",
        "base/states",
        "base/elements",
        "layout/footer",
        "components/keyframes",
        "components/blazor",
        "components/k-grid",
        "components/components",
        "components/breakpoints";
```

I'm trying to make a change to the footer partial, but changes in that file are not reflected in the compiled site.css unless I save or make a change to the site.scss file.

I'm using Visual Studio 2019 and I have WebCompiler installed as a dotnet tool. The only change I made to webcompiler.json was to disable gzip. I attempted to enable SourceMap, but WebCompiler won't generate source map files either. Please let me know if you have any questions.

**Comment by stefanloerwald** [comment]
Hi @devjklein,

Thanks for reporting this. Unfortunately, I cannot spend any time on investigating this now. It would be very helpful if you could contribute to this project by adding a unit test (there are already some, but clearly not covering this case), so you can follow the patterns there. A failing unit test would already make it much easier to pinpoint what is going wrong (I suspect the rules for detecting dependencies need a change).

Thanks
Stefan

**Comment by JustinStolle** [comment]
Looked into this and found the timestamp of the changed file wasn't being compared to determine if compilation was needed. Realized the inline comment had inadvertently caused the file that followed to be left out of the dependency list.

**Comment by devjklein** [comment]
@stefanloerwald Was @JustinStolle's fix implemented on this project? It looks like he forked but it was never merged back in.
