### ISSUE TITLE
Web compiler exited with 133

### ISSUE THREAD

**Issue by mikes-gh** [excubo-ag/WebCompiler#69]
Is there anyway to get more information from the failure.

```
  Tool 'excubo.webcompiler' (version '3.4.0-preview.1') was restored. Available commands: webcompiler
  
  Restore was successful.
/Users/mikes/Documents/Repos/MudBlazor/src/MudBlazor/MudBlazor.csproj(83,5): error MSB3073: The command "dotnet webcompiler ./Styles/MudBlazor.scss -c excubowebcompiler.json" exited with code 133.
```

I have changed the OutputStyle from Nested to Expanded and removed the Precision parameter

**Comment by stefanloerwald** [comment]
That would be nice, but it seems like one of those situations where this tool doesn't propagate the error message correctly. It would be very helpful if you could debug this and see which command fails.

**Comment by mikes-gh** [comment]
Debug gives expected results and exit code 0.
Perhaps its a packaging thing?
I am doing a 
dotnet tool restore
Tool 'excubo.webcompiler' (version '3.4.0-preview.1') was restored
in by csprog

**Comment by stefanloerwald** [comment]
Some of the package dependencies might not be compatible with net7.0 yet? It might just work in debug because of an older SDK.

**Comment by mikes-gh** [comment]
Yes I have net SDK 6 and 7 on my machine

**Comment by mikes-gh** [comment]
I'll have a look at the dependencies

**Comment by mikes-gh** [comment]
The only dependency that looks like it might need updating
Microsoft.Extensions.FileSystemGlobbing
Version 6.0.0 to. 7.0.0-rc.2.22472.3

However I tried updating that on a private package and it didn't seem to make any difference.
It does fail locally on build though with SDK 6 and 7 installed.

**Comment by stefanloerwald** [comment]
I don't think this is something we can solve here. Most likely, it's an incompatibility between net7 and the js runtime and we'll have to wait for that to be updated.

**Comment by koma-tompit** [comment]
Hi, has there been any changes around this? I've encountered the same error today. The build works fine on a Windows PC, but displays the following error on MacOS:

# Fatal error in , line 0
# Check failed: 12 == (*__error()).
#
#
#
#FailureMessage Object: 0x7ff7b43fd220

**Comment by stefanloerwald** [comment]
Hi @koma-tompit,

I'm not working with net7.0 and therefore can't meaningfully contribute to identifying the root cause of this. It's unlikely that this is an issue with this project, as previous similar issues have all been around the js runtime.

Cheers
Stefan

**Comment by koma-tompit** [comment]
> Hi @koma-tompit,
> 
> I'm not working with net7.0 and therefore can't meaningfully contribute to identifying the root cause of this. It's unlikely that this is an issue with this project, as previous similar issues have all been around the js runtime.
> 
> Cheers Stefan

It does indeed smell of a js runtime issue. Would you kindly point me in the direction of the code where it plugs into the compiler? I'll try and poke at it myself, but am quite pressed for time these days.

**Comment by mikes-gh** [comment]
@stefanloerwald I can report I am using

3.5.44 on

Apple Intel
Apple ARM
Linux x64
GitHubCodeSpaces

All without error

So I am going to close this.
