### ISSUE TITLE
Version 2.7.14 Ignore CSS Files

### ISSUE THREAD

**Issue by kooliokey** [excubo-ag/WebCompiler#70]
Our project has a mixture of CSS a SCSS files. Primarily because we added SCSS after the fact when we needed more complex stylesheets, but for simple CSS we still just use a CSS file. I recently targeted a whole folder that contains a mix of CSS and SCSS files and it started to minify the CSS files as well. Can a configuration option be added to ignore CSS files or is there a way to do it currently?

Note: Disabling minification did stop it from touching those CSS files but I want the SCSS files final CSS to be minified and it turned that off as well.

**Comment by stefanloerwald** [comment]
Hi @kooliokey,

This is not something that can be done as long as you let the compiler find all files in a folder. However, you can specify all scss files and pass them to the compiler, which will prevent it from ever considering other files from being touched.

Hope that helps
Stefan

**Comment by kooliokey** [comment]
Thanks @stefanloerwald! It looks like the latest version 3.3.Y will solve this issue for us as well with the glob pattern for finding files. Do we know when that will be available as a non-preview release? Looks like all versions since the one we are on are marked preview.

**Comment by stefanloerwald** [comment]
They are marked preview solely because a dependency is still in preview. There are no known bugs, and I'd consider it usable.
