### ISSUE TITLE
Segmentation fault during the CI

### ISSUE THREAD

**Issue by nicolas63** [excubo-ag/WebCompiler#71]
I have a segmentation fault when running my github action (https://github.com/jhipster/jhipster-dotnetcore/actions/runs/3830161376/jobs/6517684505#step:10:50) 

Do you have any idea how to solve this problem?

**Comment by stefanloerwald** [comment]
Hi @nicolas63,

Unfortunately I don't know an easy way. You'll need to replicate this somewhere where you can debug the application. Please report back with your findings so that we can improve the stability and/or error messages!

Thanks
Stefan

**Comment by nicolas63** [comment]
Hello, I have found a solution it is due to the update of the version of ubuntu runner (https://github.com/actions/runner-images/commit/9c544f47011f3fb7f13ab122927f15939d950b49) with the 20.04 it works well
