### ISSUE TITLE
Compile Error for a "Microsoft.NET.Sdk.BlazorWebAssembly" Applikation

### ISSUE THREAD

**Issue by DominikErnst** [excubo-ag/WebCompiler#77]
Compile Error for a "Microsoft.NET.Sdk.BlazorWebAssembly" Applikation in **.Net 7.**

Package 'Excubo.WebCompiler 3.5.78' has a package type 'DotnetTool' that is not supported by project 'src\Frontend\???.App'.
NU1202	Package Excubo.WebCompiler 3.5.78 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package Excubo.WebCompiler 3.5.78 supports:
  - net6.0 (.NETCoreApp,Version=v6.0) / any
  - net7.0 (.NETCoreApp,Version=v7.0) / any	

U1212	Invalid project-package combination for Excubo.WebCompiler 3.5.78. DotnetToolReference project style can only contain references of the DotnetTool type

**Comment by stefanloerwald** [comment]
Sounds like you're not installing the tool as a dotnet tool, but that you're trying to install it as a dependency instead. That's not possible and you can read about it at the top of the Readme
