### ISSUE TITLE
Compile to one .css file

### ISSUE THREAD

**Issue by KlishevichIlya** [excubo-ag/WebCompiler#78]
Is it possible to compile multiple .scss file in one .css file? (For example f1.scss, f2.scss, f3.scss to m1.css file). I tried to change Output:Directory in webcompilerconfiguration.json to **./wwwroot/styles/m1.css** , but it doesn't work. How could I resolve that issue?

**Comment by stefanloerwald** [comment]
This is not supported. I suspect that you could create one main scss file which imports the other files, but whether that works well in practice is something I can't answer.

**Comment by KlishevichIlya** [comment]
@stefanloerwald can I change the name of output file? For example I had main.scss and want to get result.css. How could I adjust the name?

**Comment by stefanloerwald** [comment]
That's also not supported. You may of course run `mv main.css result.css` right afterwards, or you simply rename your file to result.scss
