### ISSUE TITLE
.NET 8 TargetFramework

### ISSUE THREAD

**Issue by rwasef1830** [excubo-ag/WebCompiler#80]
Hey,
.NET 8.0 final dropped. Asking for simple 1 line change .net 8.0 target version on nuget :pray:
Thanks!

**Comment by stefanloerwald** [comment]
Hi @rwasef1830,

net8.0 is now a listed TargetFramework for this project. I haven't tested this, so please report back if you encounter any issues.

Best regards
Stefan
