### ISSUE TITLE
[Q] Bundling?

### ISSUE THREAD

**Issue by lonix1** [excubo-ag/WebCompiler#83]
A simple question for WebCompiler users...

This is one of the most popular static asset compile/minify/etc. tools for ASP.NET Core. I was very excited to find it.

But it does not do bundling. How are other people doing that? Any advice appreciated!

(PS: would make a good little info section in the README too. I am sure most people are happy to find this tool, but then wonder what to do about bundling.)

**Comment by stefanloerwald** [comment]
I don't use bundling and I do not have recommendations for it, sorry.
