### ISSUE TITLE
Override json config via CLI

### ISSUE THREAD

**Issue by lonix1** [excubo-ag/WebCompiler#87]
Assumptions
- scss files in `/wwwroot/` should be compiled and minified
- scss files in `/Pages/` should be compiled **but not minified**, because they are transformed by "css isolation" and placed in `obj/Release/net7.0/scopedcss/bundle/Assembly.styles.css`

I'm using this msbuild task:
```xml
<Target Name="CompileStaticAssets" AfterTargets="BeforeBuild">
  <Exec Command="dotnet webcompiler --config webcompiler.json --recursive wwwroot" StandardOutputImportance="high" />
  <Exec Command="dotnet webcompiler --config webcompiler.json --recursive Pages --minify disable" StandardOutputImportance="high" />
</Target>
```

Notice how the second command uses `--minify disable` to override the default in the config file. I assumed that would work because it's standard practice in .NET (env vars take precendence, then CLI vars, then file config, then code config).

However, it minifies those files anyway.

Can I override the json config via the CLI?

**Comment by stefanloerwald** [comment]
This sounds like a reasonable expectation. I will have to look into code for why this is not happening.
