### ISSUE TITLE
Error code 127 

### ISSUE THREAD

**Issue by nicolas63** [excubo-ag/WebCompiler#9]
On ci with github action i have this logs when webcompiler run `/home/runner/test-integration/samples/jwt-with-blazor-app/src/JhipsterSampleApplication.Client/JhipsterSampleApplication.Client.csproj(73,5): error MSB3073: The command "webcompiler -r wwwroot/content/scss -o wwwroot/content/css -z disable -p disable" exited with code 127.`

https://github.com/jhipster/jhipster-dotnetcore/pull/325/checks?check_run_id=1137238415

Can you help me ?

**Comment by stefanloerwald** [comment]
Hi @nicolas63 

Unfortunately errors like that - when they happen as part of the MSBuild process - are hard to diagnose in a build pipeline.
I recommend creating a separate build step before this one for the use of webcompiler, which should give you access to the error output of webcompiler. Then you should be able to identify the issue with the compilation process of the scss files.

**Comment by elken** [comment]
> webcompiler: not found

You forgot to either setup webcompiler as a local tool and `dotnet tool restore`  or install globally earlier.

**Comment by nicolas63** [comment]
thanks for your help it's work
