### ISSUE TITLE
"@use ... with ..." not properly handled by GetDependencies 

### ISSUE THREAD

**Issue by JustusGreiberORGADATA** [excubo-ag/WebCompiler#92]
I recently switched to the SASS module system and now use `@use` instead of `@import`. While I did that, I noticed, that sometimes my files weren't properly recompiled.

I think I know what happens: `@use` allows the [special syntax `@use ... with`](https://sass-lang.com/documentation/at-rules/use/#configuration) which I use to override some variables. For example

```scss
@use "../odid" with (
    /* Bootstrap overrides */
    $primary: colors.$orga-blue,
    $secondary: colors.$orga-gray,
    $form-feedback-valid-color: lighten(colors.$orga-orange, 20%),
);
```

The code to figure out the dependency tree does not seem to work with this syntax. If I input the example above into the function [GetDependencies](https://github.com/excubo-ag/WebCompiler/blob/f024b74afb89b7138b9f9f16a3202120404bf3e3/WebCompiler/Compile/SassCompiler.cs#L114) I get 
```scss
..\odid with 
\* Bootstrap overrides *
```

 for `file_path` and

```scss
$primary: colors.$orga-blue, 
$secondary: colors.$orga-gray, 
$form-feedback-valid-color: lightencolors.$orga-orange, 20%,
```

for `file_name`.

I haven't tried it yet, but I assume [the syntax `@use ... as`](https://sass-lang.com/documentation/at-rules/use/#choosing-a-namespace) will have similar issues.

**Comment by stefanloerwald** [comment]
Thanks for the bug report! I was able to reproduce and just submitted a fix. It's a bit hacky, so it might break things elsewhere. Please give it a try and report back any new issues.

**Comment by JustusGreiberORGADATA** [comment]
Did a quick test: The modifications I had problems with before seem to be working with the new version. Thank you for the fast fix 🎉.

If I notice that something else broke, I will report back. But so far everything is working.
