### ISSUE TITLE
WebCompiler does not work with dotnet watch anymore if using .NET 8 SDK

### ISSUE THREAD

**Issue by JustusGreiberORGADATA** [excubo-ag/WebCompiler#95]
Hi,

I create this issue more to document the issue for others, rather than to ask for a fix:

Because of changes in .NET 8 SDK the `dotnet watch` mechanism can no longer run arbitrary commands:

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-watch#arguments
https://github.com/dotnet/sdk/issues/38340

This means `dotnet watch tool webcompiler` will secretly result in `dotnet watch run tool webcompiler`, which will start the current project with the arguments `tool webcompiler` instead of running webcompiler directly. I guess if you have setup the current project to run  webcompiler on build it technically still kind of works, but certainly not as intended 😄.

**Comment by JustusGreiberORGADATA** [comment]
Oh I'm quite proud of myself, I found a dirty f-ing hack 🙃.

If you have setup webcompiler to run as part of a MSBuild Target, you can just watch that and it still kind of works.

```bash
dotnet watch build -t:CompileStaticAssets --no-restore
```

Probably not as fast, because of the MSBuild overhead, but at least it is not a full build 👍.

**Comment by stefanloerwald** [comment]
Thanks @JustusGreiberORGADATA. That workaround looks good enough for me. What a shame that running dotnet tools was dropped!
