### ISSUE TITLE
Request: prerelease build for .NET 9

### ISSUE THREAD

**Issue by nwoolls** [excubo-ag/WebCompiler#97]
Hi there. We are starting to prep our projects for .NET 9. However, we are unable to do so for any projects that use your CLI tool. We build in containers where only .NET 9 SDK is installed (based on MS's own containers).

Is it possible to get a prerelease build of your tool published to NuGet that is built with / for .NET 9?

**Comment by stefanloerwald** [comment]
While it's possible to support multiple SDKs, it increases the size of the nupkg considerably. Given that you're using the tool as part of a docker build process, I recommend separating the webcompiler step into a dedicated build stage (https://docs.docker.com/build/building/multi-stage/). Using net8.0 SDK for that stage doesn't change what SDK you can use for other parts.

Does that work for you?

**Comment by nwoolls** [comment]
@stefanloerwald that would require a fair amount of work and also break compatibility with our local build experience. We currently integrate your tool with MSBuild which works locally and in our CI process, e.g.:

```xml
    <Target Name="BeforeBuildTasks" BeforeTargets="BeforeBuild">
        <!-- Install the LibMan CLI dotnet tool w/ e.g. `dotnet tool install -g Microsoft.Web.LibraryManager.Cli` -->
        <Exec Command="libman restore"/>
        <Exec Command="npm install --omit=optional"/>
        <!-- Install the WebCompiler dotnet tool w/ e.g. `dotnet tool install -g Excubo.WebCompiler` -->
        <Exec Command="webcompiler -r ./wwwroot/scss -o ./wwwroot/out -p disable -z disable"/>
        <Exec Command="webcompiler -r ./wwwroot/scss -o ./wwwroot/out -p disable -z disable -m disable"/>
        <Exec Command="./node_modules/.bin/gulp min"/>
    </Target>
```

Do you plan on supporting .NET 9 and, if so, do you have an idea of the release schedule? I understand this is an open source project but if you are leaning towards a later release we'll need to investigate some of the other SCSS compilers, either Node based or the ones that compile on startup.

**Comment by stefanloerwald** [comment]
I haven't given this much thought so far. Keeping net8.0 support for roughly as long as it is supported would be sensible in my eyes, which is another two years. Supporting both net8 and net9 is doable, but I don't think supporting three SDKs is sensible, as the nupkg size would be excessive (maybe even exceeding the limits), so support would then move from net8/net9 to net8/net10, as net9 won't be an LTS release.

Since net9.0 is now in the RC phase, it's close enough to start supporting it now. So I'll give it a go some time soon.

**Comment by stefanloerwald** [comment]
And since I had some time now, unexpectedly, there's no version 4.0.1 out there which supports net9.0.
